[index]
name = "geral"
dimension = 1024
metric = "cosine"

[pinecone]
PINECONE_API_KEY = "c67496a3-6dec-4ee2-9fad-2d2a1a873f99"

[aws]
AWS_ACCESS_KEY_ID = "AKIAWI7G2KY5BCVZWRQO"
AWS_SECRET_ACCESS_KEY = "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"
region_name = "us-east-1"
